### ISSUE TITLE
Error: No itemStruct found

### ISSUE THREAD

**Issue by TecnoCreeper** [MarsHeer/offtiktokapi#3]
Docker container on Windows 10.

When a tiktok url is submitted the frontend shows a "Video is unavailable" message.
The backend's response status code is 500 Internal Server Error.

Opening the link from a browser logged in works fine so the video actaully exists.

Looking at the logs of the backend container I can see that there is a redirect to tiktok's login page, it then throws the `Error: No itemStruct found`

Docker container logs:

```
2024-08-03 18:23:13 offtiktokapi  | https://www.tiktok.com/login?redirect_url=https%3A%2F%2Fwww.tiktok.com%2F%40aminmellit11%2Fvideo%2F7398290691945712901%3F_t%3D8oWySW0wQpk%26_r%3D1&lang=en&enter_method=mandatory
2024-08-03 18:23:13 offtiktokapi  | Redirected
2024-08-03 18:23:13 offtiktokapi  | Error: No itemStruct found
2024-08-03 18:23:13 offtiktokapi  |     at /usr/src/app/utils/tiktok-api-wrappers.js:131:16
2024-08-03 18:23:13 offtiktokapi  |     at Generator.next (<anonymous>)
2024-08-03 18:23:13 offtiktokapi  |     at /usr/src/app/utils/tiktok-api-wrappers.js:8:71
2024-08-03 18:23:13 offtiktokapi  |     at new Promise (<anonymous>)
2024-08-03 18:23:13 offtiktokapi  |     at __awaiter (/usr/src/app/utils/tiktok-api-wrappers.js:4:12)
2024-08-03 18:23:13 offtiktokapi  |     at pullVideoData (/usr/src/app/utils/tiktok-api-wrappers.js:120:58)
2024-08-03 18:23:13 offtiktokapi  |     at /usr/src/app/utils/tiktok-api-wrappers.js:215:59
2024-08-03 18:23:13 offtiktokapi  |     at Generator.next (<anonymous>)
2024-08-03 18:23:13 offtiktokapi  |     at fulfilled (/usr/src/app/utils/tiktok-api-wrappers.js:5:58)
2024-08-03 18:23:13 offtiktokapi  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-03 18:23:13 offtiktokapi  | Cleaning up
2024-08-03 18:23:13 offtiktokapi  | Error cleaning public folder
```

I tried submitting while logged in tiktok from my host machine thinking it could help but it doesn't change anything.

**Comment by TecnoCreeper** [comment]
PS: sorry for bothering you with these bug reports :P
